apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.jobName }}-spark
  description: ${{ values.description || 'AWS EMR Spark Pipeline' }}
  annotations:
    backstage.io/managed-by-location: url:./catalog-info.yaml
    backstage.io/managed-by-origin-location: url:./catalog-info.yaml
    aws.com/region: ${{ values.region }}
    emr.aws.com/release-label: ${{ values.emrReleaseLabel }}
    emr.aws.com/instance-type: ${{ values.instanceType }}
    emr.aws.com/instance-count: '${{ values.instanceCount }}'
  labels:
    cloud: aws
    type: data-pipeline
    service: emr
spec:
  type: service
  lifecycle: production
  owner: data-infrastructure-team
  system: data-pipelines
  dependsOn:
    - resource:aws:emr:cluster
  providesApis:
    - spark-job-api
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: emr-cluster
  description: Amazon EMR Cluster for Spark processing
  annotations:
    aws.com/region: ${{ values.region }}
    emr.aws.com/release-label: ${{ values.emrReleaseLabel }}
  labels:
    cloud: aws
    type: data-processing
spec:
  type: processing-cluster
  lifecycle: production
  owner: data-infrastructure-team
  system: data-pipelines
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: spark-job-api
  description: API for interacting with Spark jobs
spec:
  type: openapi
  lifecycle: production
  owner: data-infrastructure-team
  system: data-pipelines
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Spark Jobs API
      description: API for managing Spark jobs
    paths:
      /jobs:
        post:
          summary: Submit a Spark job
          responses:
            '200':
              description: Job submitted successfully
