apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: terraform-templates
  description: Collection of Terraform infrastructure templates for AWS, Azure, and GCP
  annotations:
    github.com/project-slug: ${{ values.destination.owner + '/' + values.destination.repo }}
    backstage.io/techdocs-ref: dir:.
  tags:
    - terraform
    - infrastructure
    - aws
    - azure
    - gcp
  links:
    - url: https://backstage.io/docs/features/software-templates/
      title: Backstage Templates Documentation
      icon: docs
spec:
  owner: platform-team
  targets:
    # AWS templates
    - ./templates/aws/lambda-function/template.yaml
    - ./templates/aws/sns-topic/template.yaml
    - ./templates/aws/sagemaker-pipeline/template.yaml
    - ./templates/aws/sagemaker-endpoint/template.yaml
    - ./templates/aws/spark-pipeline/template.yaml

    # Azure templates
    - ./templates/azure/ml-pipeline/template.yaml
    - ./templates/azure/kubeflow-pipeline/template.yaml
    - ./templates/azure/spark-pipeline/template.yaml
    - ./templates/azure/function-endpoint/template.yaml

    # GCP templates
    - ./templates/gcp/cloud-run/template.yaml
    - ./templates/gcp/vertex-pipeline/template.yaml
    - ./templates/gcp/kubeflow-pipeline/template.yaml
    - ./templates/gcp/dataflow-pipeline/template.yaml

    # RDS templates
    # - ./templates/rds-temp/template.yaml
