apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.clusterName }}-kubeflow-pipeline
  description: ${{ values.description || 'Kubeflow Pipeline running on AKS cluster in Azure' }}
  annotations:
    backstage.io/managed-by-location: url:./catalog-info.yaml
    backstage.io/managed-by-origin-location: url:./catalog-info.yaml
    azure.com/location: ${{ values.location }}
    azure.com/resource-group: ${{ values.resourceGroupName }}
    kubernetes.io/version: ${{ values.kubernetesVersion }}
    kubeflow.org/version: ${{ values.kubeflowVersion }}
  labels:
    cloud: azure
    type: ml-pipeline
    ml-platform: kubeflow
spec:
  type: service
  lifecycle: production
  owner: ml-platform-team
  system: ml-pipelines
  dependsOn:
    - resource:azure:aks:${{ values.clusterName }}
  providesApis:
    - azure-kubeflow-pipeline-api
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ values.clusterName }}
  description: AKS Cluster hosting Kubeflow Pipeline
  annotations:
    azure.com/location: ${{ values.location }}
    azure.com/resource-group: ${{ values.resourceGroupName }}
    kubernetes.io/version: ${{ values.kubernetesVersion }}
  labels:
    cloud: azure
    type: kubernetes
spec:
  type: kubernetes-cluster
  lifecycle: production
  owner: ml-platform-team
  system: ml-pipelines
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: azure-kubeflow-pipeline-api
  description: API for interacting with Kubeflow Pipelines on Azure
spec:
  type: openapi
  lifecycle: production
  owner: ml-platform-team
  system: ml-pipelines
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: Azure Kubeflow Pipelines API
      description: API for managing ML pipelines in Kubeflow on Azure
    paths:
      /pipelines:
        get:
          summary: List pipelines
          responses:
            '200':
              description: List of pipelines
