apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-gcp-kubeflow-pipeline
  title: GCP Kubeflow Pipeline on GKE
  description: Deploy Kubeflow pipelines on Google Kubernetes Engine using Terraform
  tags:
    - terraform
    - gcp
    - kubernetes
    - kubeflow
    - ml
    - pipeline
spec:
  owner: ml-platform-team
  type: infrastructure

  parameters:
    - title: GCP Kubeflow Pipeline Information
      required:
        - projectId
        - clusterName
      properties:
        projectId:
          title: GCP Project ID
          type: string
          description: Google Cloud Project ID
          ui:autofocus: true
        clusterName:
          title: GKE Cluster Name
          type: string
          description: Name of the Google Kubernetes Engine cluster
        region:
          title: GCP Region
          type: string
          description: GCP region to deploy to
          default: us-central1
        zone:
          title: GCP Zone
          type: string
          description: GCP zone to deploy to
          default: us-central1-a
        kubernetesVersion:
          title: Kubernetes Version
          type: string
          description: Version of Kubernetes to use
          default: 1.24
        machineType:
          title: Machine Type
          type: string
          description: Machine type for GKE nodes
          default: e2-standard-4
        nodeCount:
          title: Node Count
          type: number
          description: Number of nodes in the GKE cluster
          default: 3
        kubeflowVersion:
          title: Kubeflow Version
          type: string
          description: Version of Kubeflow to deploy
          default: 1.7.0

  steps:
    - id: fetch-template
      name: Fetch Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          projectId: ${{ parameters.projectId }}
          clusterName: ${{ parameters.clusterName }}
          region: ${{ parameters.region }}
          zone: ${{ parameters.zone }}
          kubernetesVersion: ${{ parameters.kubernetesVersion }}
          machineType: ${{ parameters.machineType }}
          nodeCount: ${{ parameters.nodeCount }}
          kubeflowVersion: ${{ parameters.kubeflowVersion }}

  output:
    links:
      - title: GitHub Repository
        url: ${{ steps.publish.output.remoteUrl || '/' }}
      - title: Google Cloud Console
        url: https://console.cloud.google.com
