version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - ../catalog-info.yaml:/app/catalog-info.yaml
      - ../templates:/app/templates
    environment:
      - BACKSTAGE_API_URL=http://localhost:7007/api
      - TEMPLATES_DIR=/app/templates
      - CATALOG_FILE=/app/catalog-info.yaml
      - BACKSTAGE_AUTH_TOKEN=development
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    networks:
      - backstage-deploy

  # Optional: If you want to run this alongside Backstage
  # backstage:
  #   image: backstage/backstage
  #   ports:
  #     - "7007:7007"
  #   networks:
  #     - backstage-network

networks:
  backstage-deploy:
    external: true 