apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-aws-sagemaker-endpoint
  title: AWS SageMaker Endpoint
  description: Deploy a SageMaker endpoint for model serving using Terraform
  tags:
    - terraform
    - aws
    - sagemaker
    - ml
    - inference
spec:
  owner: ml-platform-team
  type: infrastructure

  parameters:
    - title: SageMaker Endpoint Information
      required:
        - endpointName
        - modelName
        - roleArn
      properties:
        endpointName:
          title: Endpoint Name
          type: string
          description: Name of the SageMaker endpoint
          ui:autofocus: true
        modelName:
          title: Model Name
          type: string
          description: Name of the model to deploy
        roleArn:
          title: IAM Role ARN
          type: string
          description: ARN of the IAM role that SageMaker can assume to perform tasks
        description:
          title: Description
          type: string
          description: Description of the endpoint
        instanceType:
          title: Instance Type
          type: string
          description: Amazon EC2 instance type for the endpoint
          default: ml.t2.medium
        initialInstanceCount:
          title: Initial Instance Count
          type: number
          description: Initial number of instances for the endpoint
          default: 1
        modelDataUrl:
          title: Model Data URL
          type: string
          description: S3 URL to the model artifacts
        containerImage:
          title: Container Image
          type: string
          description: URI to the container image for model inference
          default: 763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-inference:2.6.3-cpu

  steps:
    - id: fetch-template
      name: Fetch Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          endpointName: ${{ parameters.endpointName }}
          modelName: ${{ parameters.modelName }}
          roleArn: ${{ parameters.roleArn }}
          description: ${{ parameters.description }}
          instanceType: ${{ parameters.instanceType }}
          initialInstanceCount: ${{ parameters.initialInstanceCount }}
          modelDataUrl: ${{ parameters.modelDataUrl }}
          containerImage: ${{ parameters.containerImage }}

  output:
    links:
      - title: GitHub Repository
        url: ${{ steps.publish.output.remoteUrl || '/' }}
      - title: AWS SageMaker Console
        url: https://console.aws.amazon.com/sagemaker/home#/endpoints
