apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-gcp-dataflow-pipeline
  title: GCP Dataflow Pipeline
  description: Deploy a Google Dataflow pipeline for data processing using Terraform
  tags:
    - terraform
    - gcp
    - dataflow
    - data-pipeline
    - big-data
spec:
  owner: data-platform-team
  type: infrastructure

  parameters:
    - title: GCP Dataflow Pipeline Information
      required:
        - projectId
        - jobName
      properties:
        projectId:
          title: GCP Project ID
          type: string
          description: Google Cloud Project ID
          ui:autofocus: true
        jobName:
          title: Job Name
          type: string
          description: Name of the Dataflow job
        region:
          title: GCP Region
          type: string
          description: GCP region to deploy to
          default: us-central1
        templatePath:
          title: Template Path
          type: string
          description: GCS path to the Dataflow template
        tempLocation:
          title: Temp Location
          type: string
          description: GCS path for temporary files
        serviceAccount:
          title: Service Account
          type: string
          description: Service account to run the Dataflow job
        machineType:
          title: Machine Type
          type: string
          description: Machine type for Dataflow workers
          default: n1-standard-2
        maxWorkers:
          title: Max Workers
          type: number
          description: Maximum number of workers
          default: 5
        network:
          title: VPC Network
          type: string
          description: VPC network to use for the Dataflow job
        subnetwork:
          title: Subnetwork
          type: string
          description: Subnetwork to use for the Dataflow job

  steps:
    - id: fetch-template
      name: Fetch Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          projectId: ${{ parameters.projectId }}
          jobName: ${{ parameters.jobName }}
          region: ${{ parameters.region }}
          templatePath: ${{ parameters.templatePath }}
          tempLocation: ${{ parameters.tempLocation }}
          serviceAccount: ${{ parameters.serviceAccount }}
          machineType: ${{ parameters.machineType }}
          maxWorkers: ${{ parameters.maxWorkers }}
          network: ${{ parameters.network }}
          subnetwork: ${{ parameters.subnetwork }}

  output:
    links:
      - title: GitHub Repository
        url: ${{ steps.publish.output.remoteUrl || '/' }}
      - title: Google Cloud Console
        url: https://console.cloud.google.com/dataflow
