apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.topicName }}
  description: ${{ values.description || 'AWS SNS Topic' }}
  annotations:
    backstage.io/managed-by-location: url:./catalog-info.yaml
    backstage.io/managed-by-origin-location: url:./catalog-info.yaml
    aws.com/region: ${{ values.region }}
    sns.aws.com/fifo: "${{ values.fifoTopic || 'false' }}"
    sns.aws.com/content-based-deduplication: "${{ values.contentBasedDeduplication || 'false' }}"
  labels:
    cloud: aws
    type: messaging
    service: sns
spec:
  type: messaging
  lifecycle: production
  owner: infrastructure-team
  system: messaging-services
  providesApis:
    - ${{ values.topicName }}-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.topicName }}-api
  description: API for interacting with the SNS Topic
spec:
  type: openapi
  lifecycle: production
  owner: infrastructure-team
  system: messaging-services
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: ${{ values.topicName }} API
      description: API for publishing messages to the SNS topic
    paths:
      /publish:
        post:
          summary: Publish a message to the topic
          responses:
            '200':
              description: Message published successfully
