apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.pipelineName }}
  description: ${{ values.description || 'AWS SageMaker Pipeline' }}
  annotations:
    backstage.io/managed-by-location: url:./catalog-info.yaml
    backstage.io/managed-by-origin-location: url:./catalog-info.yaml
    aws.com/region: ${{ values.region }}
    sagemaker.aws.com/pipeline-type: ${{ values.pipelineType || 'model-building' }}
    sagemaker.aws.com/execution-role: ${{ values.executionRole }}
  labels:
    cloud: aws
    type: ml-pipeline
    service: sagemaker
spec:
  type: service
  lifecycle: production
  owner: ml-platform-team
  system: ml-pipelines
  dependsOn:
    - resource:aws:sagemaker:pipeline-service
  providesApis:
    - ${{ values.pipelineName }}-api
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: sagemaker-pipeline-service
  description: SageMaker Pipeline Service
  annotations:
    aws.com/region: ${{ values.region }}
  labels:
    cloud: aws
    type: ml-service
spec:
  type: ml-service
  lifecycle: production
  owner: ml-platform-team
  system: ml-pipelines
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.pipelineName }}-api
  description: API for interacting with SageMaker Pipeline
spec:
  type: openapi
  lifecycle: production
  owner: ml-platform-team
  system: ml-pipelines
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: ${{ values.pipelineName }} API
      description: API for managing SageMaker Pipeline
    paths:
      /pipelines/${{ values.pipelineName }}/executions:
        post:
          summary: Start pipeline execution
          responses:
            '200':
              description: Pipeline execution started
