apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.serviceName }}
  description: ${{ values.description || 'GCP Cloud Run Service' }}
  annotations:
    backstage.io/managed-by-location: url:./catalog-info.yaml
    backstage.io/managed-by-origin-location: url:./catalog-info.yaml
    gcp.com/project-id: ${{ values.projectId }}
    gcp.com/region: ${{ values.region }}
    cloud-run.gcp.com/image: ${{ values.image }}
    cloud-run.gcp.com/cpu: ${{ values.cpu }}
    cloud-run.gcp.com/memory: ${{ values.memory }}
    cloud-run.gcp.com/max-instances: '${{ values.maxInstances }}'
  labels:
    cloud: gcp
    type: serverless
    service: cloud-run
spec:
  type: service
  lifecycle: production
  owner: cloud-infrastructure-team
  system: cloud-services
  providesApis:
    - ${{ values.serviceName }}-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.serviceName }}-api
  description: API provided by the ${{ values.serviceName }} Cloud Run service
spec:
  type: openapi
  lifecycle: production
  owner: cloud-infrastructure-team
  system: cloud-services
  definition: |
    openapi: "3.0.0"
    info:
      version: 1.0.0
      title: ${{ values.serviceName }} API
      description: API for the ${{ values.serviceName }} Cloud Run service
    paths:
      /:
        get:
          summary: Default endpoint
          responses:
            '200':
              description: Successful response
