apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-aws-sns-topic
  title: AWS SNS Topic
  description: Create a new AWS SNS topic with subscriptions using Terraform
  tags:
    - terraform
    - aws
    - sns
    - messaging
spec:
  owner: infrastructure-team
  type: infrastructure

  parameters:
    - title: SNS Topic Information
      required:
        - topicName
      properties:
        topicName:
          title: Topic Name
          type: string
          description: Name of the SNS topic
          ui:autofocus: true
        displayName:
          title: Display Name
          type: string
          description: Display name of the SNS topic
        subscriptions:
          title: Subscriptions
          type: array
          description: List of subscriptions to the SNS topic
          items:
            type: object
            required:
              - protocol
              - endpoint
            properties:
              protocol:
                title: Protocol
                type: string
                description: Protocol for the subscription
                enum:
                  - email
                  - email-json
                  - sms
                  - sqs
                  - lambda
                  - http
                  - https
              endpoint:
                title: Endpoint
                type: string
                description: Endpoint for the subscription
        fifoTopic:
          title: FIFO Topic
          type: boolean
          description: Whether the topic is a FIFO (First-In-First-Out) topic
          default: false

  steps:
    - id: fetch-template
      name: Fetch Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          topicName: ${{ parameters.topicName }}
          displayName: ${{ parameters.displayName }}
          subscriptions: ${{ parameters.subscriptions }}
          fifoTopic: ${{ parameters.fifoTopic }}

  output:
    links:
      - title: GitHub Repository
        url: ${{ steps.publish.output.remoteUrl || '/' }}
      - title: AWS Console
        url: https://console.aws.amazon.com/sns/v3/home#/topics
