apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: terraform-gcp-cloud-run
  title: GCP Cloud Run Service
  description: Create a new Cloud Run service on Google Cloud Platform using Terraform
  tags:
    - terraform
    - gcp
    - cloud-run
    - serverless
spec:
  owner: cloud-infrastructure-team
  type: infrastructure

  parameters:
    - title: Cloud Run Service Information
      required:
        - serviceName
        - projectId
        - region
      properties:
        serviceName:
          title: Service Name
          type: string
          description: Name of the Cloud Run service
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: Description of the Cloud Run service
        projectId:
          title: GCP Project ID
          type: string
          description: Google Cloud Project ID where the service will be deployed
        region:
          title: GCP Region
          type: string
          description: GCP region to deploy to
          default: us-central1
        image:
          title: Container Image
          type: string
          description: Container image to deploy (e.g., gcr.io/PROJECT_ID/IMAGE:TAG)
          default: gcr.io/cloudrun/hello
        cpu:
          title: CPU Allocation
          type: string
          description: CPU allocation for the service
          default: '1'
        memory:
          title: Memory Allocation
          type: string
          description: Memory allocation for the service
          default: '256Mi'
        maxInstances:
          title: Max Instances
          type: number
          description: Maximum number of instances
          default: 10

  steps:
    - id: fetch-template
      name: Fetch Template
      action: fetch:template
      input:
        url: ./skeleton
        values:
          serviceName: ${{ parameters.serviceName }}
          description: ${{ parameters.description }}
          projectId: ${{ parameters.projectId }}
          region: ${{ parameters.region }}
          image: ${{ parameters.image }}
          cpu: ${{ parameters.cpu }}
          memory: ${{ parameters.memory }}
          maxInstances: ${{ parameters.maxInstances }}

  output:
    links:
      - title: GitHub Repository
        url: ${{ steps.publish.output.remoteUrl || '/' }}
      - title: Google Cloud Console
        url: https://console.cloud.google.com/run?project=${{ parameters.projectId }}
