apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    backstage.io/managed-by-location: url:${values.repoUrl}
    backstage.io/managed-by-origin-location: url:${values.repoUrl}
  tags:
    - terraform
    - aws
    - rds
    - postgres
    - infrastructure
    - database
spec:
  type: infrastructure
  owner: ${{ values.owner | default("infrastructure-team") }}
  lifecycle: experimental
  system: database
  dependsOn:
    - resource:aws-vpc
    - resource:aws-subnet
  providesApis:
    - postgresql
